### ISSUE TITLE
API is having issues

### ISSUE THREAD

**Issue by autarch** [axisbits/covid-api#13] opened 2021-01-20 22:26 UTC
I'm seeing a lot of 502 errors and even the docs are slow to load or failing to load. Is there a better place to report this?

**Comment by auge8472** [comment] 2021-01-21 21:37
I can confirm the issue. :-(

**Comment by elitemaks** [comment] 2021-01-22 11:55
@auge8472 @autarch thanks for reporting! We have upgraded our server, it failed to process an increased number of requests. 
Please let us know if you have such issues in the next following days.

**Comment by autarch** [comment] 2021-01-23 17:07
@elitemaks I'm still seeing the 502 errors right now, and it's very slow even when it doesn't return a 502.

**Comment by auge8472** [comment] 2021-01-26 14:33
I do receive data again. I can not confirm the observartions made by @autarch. I myself requests once a day automatically data for one country and do not see if this is possibly slow. Even when I start the same request with the browser (via the address bar) it works in a (for me) normal speed.

**Comment by elitemaks** [comment] 2021-01-26 14:59
Hi @auge8472 , thank you for your comment. We made some changes to the server to address the increased load. 
@autarch please let us know too if you still experience these issues.

**Comment by elitemaks** [comment] 2021-01-29 11:42
Hi @autarch and @auge8472. We monitored the server for a few days and it seems to be working fine now. If you are still getting errors - please let us know. Otherwise, we will close this issue next week.

**Comment by autarch** [comment] 2021-01-29 16:06
I haven't seen any issues for the last few days.

**Closed as completed** 2021-02-01 16:24 UTC
